services:
  nextjs:
    container_name: crazy-wolf-nextjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - crazy-wolf-net

networks:
  crazy-wolf-net:
    driver: bridge
