services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: crazy-wolf-admin-app
    container_name: crazy-wolf-admin-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - crazy-wolf-net
    # environment:
    #   - NODE_ENV=production
    #   - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    #   - DATABASE_URL=${DATABASE_URL}
    #   - JWT_SECRET=${JWT_SECRET}
    #   - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
    #   - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
    #   - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    command: >
      sh -c "
        echo 'Building Next.js...';
        npm install &&
        npm run build &&
        npm run start
      "
    ports:
      - "3002:3000"

  webserver:
    image: nginx:alpine
    container_name: crazy-wolf-webserver
    restart: unless-stopped
    ports:
      - "8003:80"
      - "3004:443"
    volumes:
      - ./docker/nginx/public.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - crazy-wolf-net

networks:
  crazy-wolf-net:
    driver: bridge 